import smtplib
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

# SMTP server configuration
SMTP_SERVER = "smtp.freesmtpservers.com"
SMTP_PORT = 25

# Real invoice PDFs generated by the backend (app/pdf.py) during enrollment.
GENERATED_DIR = Path(__file__).resolve().parent.parent / "backend" / "generated"


def latest_invoice_pdf() -> Path:
    """Return the most recently generated invoice PDF for the test attachment."""
    invoices = sorted(GENERATED_DIR.glob("invoice_*.pdf"), key=lambda p: p.stat().st_mtime)
    if not invoices:
        raise FileNotFoundError(
            f"No invoice PDFs found in {GENERATED_DIR}. "
            "Enroll a test participant via the backend first (e.g. /enroll) to generate one."
        )
    return invoices[-1]


def send_email(sender, recipient, subject, body, attachment_path: Path | None = None):
    # Build the email message
    msg = MIMEMultipart()
    msg["From"] = sender
    msg["To"] = recipient
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain"))

    if attachment_path is not None:
        pdf_bytes = Path(attachment_path).read_bytes()
        attachment = MIMEApplication(pdf_bytes, _subtype="pdf")
        attachment.add_header(
            "Content-Disposition", "attachment", filename=Path(attachment_path).name
        )
        msg.attach(attachment)

    try:
        # Connect to the SMTP server (no auth needed)
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT, timeout=10) as server:
            server.ehlo()
            server.sendmail(sender, recipient, msg.as_string())
        print("Email sent successfully!")
    except Exception as e:
        print(f"Failed to send email: {e}")

if __name__ == "__main__":
    invoice_pdf = latest_invoice_pdf()
    print(f"Attaching invoice: {invoice_pdf.name}")
    send_email(
        sender="test@example.com",
        recipient="recipient@example.com",
        subject="Test Email",
        body="This is a test email sent via smtp.freesmtpservers.com, with an invoice PDF attached.",
        attachment_path=invoice_pdf,
    )
